### ISSUE TITLE
EAN 128格式条码 扫码结果字符串里开头会多出"]C1"字符

### ISSUE THREAD

**Issue by yeyesama** [maning0303/MNMLKitScanner#7]
如题, 使用Demo测试了EAN 128编码的条码, 发现会多出"]C1"字符, barcode.getRawValue()得到的结果是包含"]C1"的, 作者不考虑用barcode.getDisplayValue()的值作为扫码结果吗. 🍰
条码生成网站: 
https://www.barcode-generator.de/V2/zh/index.jsp
测试条码类型: EAN 128编码 🍨 
MLKit有类似issue
https://github.com/googlesamples/mlkit/issues/348

**Comment by maning0303** [comment]
@yeyesama 多谢提醒和建议，新版本已经在修改

**Comment by maning0303** [comment]
@yeyesama 最新版本已经修改，感谢反馈
