### ISSUE TITLE
可以添加设置扫码框的大小么

### ISSUE THREAD

**Issue by yangqb** [maning0303/MNMLKitScanner#8]
可以添加设置扫码框的大小么

**Comment by maning0303** [comment]
暂时不可以，非全屏模式下默认屏幕宽度的7/10，后续会添加宽度比例属性

**Comment by maning0303** [comment]
@yangqb 最新版本已经支持自定义扫码框大小，请查看最新版本Demo，有什么问题再反馈，谢谢
